name: Run DB Tests in Docker

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests via docker-compose
        run: |
          docker compose build tests
          docker compose up tests
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml
      
      - name: Display test results
        if: always()
        run: cat test-results/results.xml
      
